#!/bin/bash


a=${install_dir}/${jenkins_dir}/jenkins.war
b=${log_dir}/${jenkins_dir}/jenkins.log


if [ "$1" == "start" ];then
    nohup java -jar $a --httpPort=$port --httpListenAddress=$listen &>> $b &
elif [ "$1" == "stop" ];then
    pi=`ps -aux | grep jenkins -jar $a --httpPort=$port`
    [ ! $pi ] && exit 3 || pid=`echo $pi | awk '{print $2}'`
    kill -9 $pid
elif [ "$1" == "status" ];then
    pi=`ps -aux | grep jenkins -jar $a --httpPort=$port`
    [ ! $pi ] && echo "jenkins ok" || echo "jenkins error"
else
    echo "start | stop | status"
fi