#!/usr/bin/env bash


qiu_x=15 #小球的竖
qiu_y=30 #小球的横
hua=0
xian=0
xiao=0
xian_x=()
xian_y=()
xiao_x=()
xiao_y=()
p_exit() {
echo -e "\033[?25h"    #显示光标
stty echo    #显示输出内容
zhengli
exit
}

zhengli(){
local i
for i in `seq 0 $xian`
do
    echo "${xian_x[$i]},${xian_y[$i]}" >> good.txt
done
sort good.txt | uniq > boy.txt #不重复的写进去
for i in `seq 0 $xiao` #再后面增加
do
    echo "${xiao_x[$i]},${xiao_y[$i]}" >> boy.txt
done
sort boy.txt | uniq -u > goodboy.txt #d地图
rm -rf good.txt boy.txt
}

trap "p_exit;" INT TERM    #当按ctl+c强制退出则执行p_exit函数内容

qiu_clear() {
if [ $hua -eq 1 ];then
    echo -e "\033["40"m\033[${qiu_x};${qiu_y}H       \033[0m"
    xiao_x[$xiao]=$qiu_x
    xiao_y[$xiao]=$qiu_y
    let xiao++
fi
}

zengjia() {
    xian_x[$xian]=$qiu_x
    xian_y[$xian]=$qiu_y
    let xian++
}

shang() { #向上移动先把原来坐标小点抹去，把x轴-1
    qiu_clear
    let qiu_x-=1
    echo -e "\033["44"m\033[${qiu_x};${qiu_y}H  \033[0m"
    zengjia
}

xia() {
    qiu_clear
    let qiu_x+=1
    echo -e "\033["44"m\033[${qiu_x};${qiu_y}H  \033[0m"
    zengjia
}

zuo() {
    qiu_clear
    let qiu_y-=2 #像素问题
    echo -e "\033["44"m\033[${qiu_x};${qiu_y}H  \033[0m"
    zengjia
}

you() {
    qiu_clear
    let qiu_y+=2
    echo -e "\033["44"m\033[${qiu_x};${qiu_y}H  \033[0m"
    zengjia
}

#脚本主体
clear
echo -e "\033[?25l" #隐藏光标
stty -echo #隐藏输入
echo -e "\033["37"m\033[1;1H wasd移动,按空格切换绘画模式,p退出\033[0m"
echo -e "\033["44"m\033[${qiu_x};${qiu_y}H  \033[0m" #先显示一遍小点
zengjia
while [ 1 ] #支持大小写操作
do
    read -s -n 1 option
    if [[ $option == "w" || $option == "W" ]];then
        shang
    elif [[ $option == "s" ||  $option == "S" ]];then
        xia
    elif [[ $option == "a" ||  $option == "A" ]];then
        zuo
    elif [[ $option == "d" ||  $option == "D" ]];then
        you
    elif [[ "[$option]" == "[]" ]];then #按空格绘制
        if [ $hua -eq 1 ];then
            hua=0
        else
            hua=1
        fi
    elif [[ $option == "p" ||  $option == "P" ]];then
        p_exit
    fi
done
