#!/usr/bin/env bash


tiqu() {
local a b i
abc_x=()
abc_y=()
a=`wc -l goodboy.txt | awk '{print $1}'`
b=0
for i in `seq 1 $a` #提取到数组里
do
    abc_x[$b]=`sed -n "${i}p" goodboy.txt | awk -F',' '{print $1}'`
    abc_y[$b]=`sed -n "${i}p" goodboy.txt | awk -F',' '{print $2}'`
    let b++
done
}

xianshi() {
local a b i
a=`echo ${#abc_x[*]}`
b=`echo $[a-1]`
for i in `seq 0 $b`
do
    echo -e "\033["44"m\033[${abc_x[$i]};${abc_y[$i]}H  \033[0m"
done
}


tiqu
xianshi
