#!/usr/bin/env bash

get_xian-draw() {
    [ $language -eq 1 ] && echo "不用下载" || ehco "Do not download"
}

install_xian-draw() {
    cp conf/alone/xian-draw /usr/local/bin/xian-draw
    chmod +x /usr/local/bin/xian-draw

    [ $language -eq 1 ] && echo "xian-draw安装完毕，使用xian-draw 显示画的图" || ehco "cha installation is completed, use xian-draw Display picture"
}

remove_xian-draw() {
    rm -rf /usr/local/bin/xian-draw
    [ $language -eq 1 ] && echo "xian-draw已卸载" || ehco "xian-draw Uninstalled"
}


info_xian-draw() {
    if [ $language -eq 1 ];then
        echo "名字：xian-draw"
        echo
        echo "类型：游戏"
        echo
        echo "版本：1.0"
        echo
        echo "作者：未知"
        echo
        echo "介绍：显示画的图"
        echo
        echo "提示：无"
        echo
        echo "使用：xian-draw命令即可显示用drawing脚本画的图，需要读取存档文件"
    else
        echo "Name：xian-draw"
        echo
        echo "Type：game"
        echo
        echo "version：1.0"
        echo
        echo "Author：unknown"
        echo
        echo "Introduction：Display picture"
        echo
        echo "Prompt：none"
        echo
        echo "use：xian-draw command to display the drawing script drawing, you need to read the archive file"
    fi
}
