#!/usr/bin/env bash

get_xian_draw() {
    [ $language -eq 1 ] && echo "不用下载" || ehco "Do not download"
}

install_xian_draw() {
    cp conf/alone/xian-draw /usr/local/bin/xian-draw
    chmod +x /usr/local/bin/xian-draw

    echo "xian-draw" >> conf/installed.txt
    [ $language -eq 1 ] && echo "xian-draw安装完毕，使用xian-draw 显示画的图" || ehco "cha installation is completed, use xian-draw Display picture"
}

remove_xian_draw() {
    rm -rf /usr/local/bin/xian-draw
    [ $language -eq 1 ] && echo "xian-draw已卸载" || ehco "xian-draw Uninstalled"
}


info_xian_draw() {
    if [ $language -eq 1 ];then
        echo "名字：xian-draw
        
类型：游戏

版本：1.0

作者：未知

介绍：显示画的图

提示：无

使用：xian-draw命令即可显示用drawing脚本画的图，需要读取存档文件"
    else
        echo "Name：xian-draw
        
Type：game

version：1.0

Author：unknown

Introduction：Display picture

Prompt：none

use：xian-draw command to display the drawing script drawing, you need to read the archive file"
    fi
}
