#!/usr/bin/env bash

get_xian-draw() {
    [ $language -eq 1 ] && echo "不用下载" || ehco "Do not download"
}

install_xian-draw() {
    cp conf/alone/xian-draw /usr/local/bin/xian-draw
    chmod +x /usr/local/bin/xian-draw

    [ $language -eq 1 ] && echo "xian-draw安装完毕，使用xian-draw 显示画的图" || ehco "cha installation is completed, use xian-draw Display picture"
}

remove_xian-draw() {
    rm -rf /usr/local/bin/xian-draw
    [ $language -eq 1 ] && echo "xian-draw已卸载" || ehco "xian-draw Uninstalled"
}


info_xian-draw() {
    if [ $language -eq 1 ];then
        echo "功能：显示画的图"
        echo
        echo "使用：xian-draw"
    else
        echo "Function: Display picture"
        echo
        echo "use：xian-draw"
    fi
}
