#!/bin/bash



a=${install_dir}/${redis_dir}/bin/redis-server
b=${install_dir}/${redis_dir}/cluster/
c=${log_dir}/${redis_dir}


start() {
    netstat -unltp | awk -F':' '{print $2}' | grep -w ${port} &> /dev/null
    if [ $? -ne 0 ];then
        $a $b/${port}/${port}.conf >> $c/redis_${1}.log &
    fi
}

stop() {
    netstat -unltp | awk -F':' '{print $2}' | grep -w ${port} &> /dev/null
    if [ $? -eq 0 ];then
        pid=`cat ${install_dir}/${redis_dir}/cluster/${1}/redis_${1}.pid `
        kill -9 $pid &> /dev/null
    fi
}

status() {
    netstat -unltp | awk -F':' '{print $2}' | grep -w ${port} &> /dev/null
    [ $? -eq 0 ] && echo "redis port:${1} ok" || echo "redis port:${1} error"
}


if [ "$1" == "start" ];then
    start
elif [ "$1" == "stop" ];then
    stop
elif [ "$1" == "status" ];then
    status
else
    echo "start | stop | status"
fi
